name: Test PSK Server and Client

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Start server in background
      run: |
        python server.py &
        SERVER_PID=$!
        echo "SERVER_PID=$SERVER_PID" >> $GITHUB_ENV
        echo $SERVER_PID > server.pid
        # Wait for server to start
        sleep 3
    
    - name: Verify server is running
      run: |
        if ps -p $SERVER_PID > /dev/null; then
          echo "Server is running with PID $SERVER_PID"
        else
          echo "Server failed to start"
          exit 1
        fi
    
    - name: Test client connectivity
      run: |
        python client.py
    
    - name: Stop server
      run: |
        kill $SERVER_PID || true
      if: always()